name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: pip install mock

      - name: Run tests
        run: |
          python3 -m unittest tests.UuidGenerator
          python3 -m unittest tests.DateValidator
          python3 -m unittest tests.EmployeeTaskMock
